# Dictionaries of session meta-data per animal
import numpy as np

# Enter ppilot metadata starting with main task day 1
# Leave 'scan' as np.nan (not a number)
sosalab = {

    'pp01': ({'date': '2026_06_03', 'scene': 'FiveTower_Stay', 'session': 1, 'scan': np.nan, 'exp_day': 1,
                'GD': np.nan, 'pregnant': False, 'rig': 'omen-vr',},
             {'date': '2026_06_04', 'scene': 'FiveTower_Stay', 'session': 1, 'scan': np.nan, 'exp_day': 2, 
                'GD': np.nan, 'pregnant': False, 'rig': 'omen-vr',},
             {'date': '2026_06_05', 'scene': 'FiveTower_Switch_BlackoutDelay', 'session': 2, 'scan': np.nan, 'exp_day': 3, 
                'GD': np.nan, 'pregnant': False, 'rig': 'omen-vr',},
            {'date': '2026_06_06', 'scene': 'FiveTower_Stay_BlackoutDelay', 'session': 1, 'scan': np.nan, 'exp_day': 4, 
                'GD': np.nan, 'pregnant': False, 'rig': 'omen-vr',},
            {'date': '2026_06_12', 'scene': 'FiveTower_Switch_BlackoutDelay', 'session': 1, 'scan': np.nan, 'exp_day': 5, 
                'GD': np.nan, 'pregnant': False, 'rig': 'omen-vr',},
            {'date': '2026_06_13', 'scene': 'FiveTower_Stay_BlackoutDelay', 'session': 1, 'scan': np.nan, 'exp_day': 6, 
                'GD': np.nan, 'pregnant': False, 'rig': 'omen-vr',},
            {'date': '2026_06_14', 'scene': 'FiveTower_Switch_BlackoutDelay', 'session': 1, 'scan': np.nan, 'exp_day': 7, 
                'GD': np.nan, 'pregnant': False, 'rig': 'omen-vr',},
            {'date': '2026_06_15', 'scene': 'FiveTower_Stay_BlackoutDelay', 'session': 3, 'scan': np.nan, 'exp_day': 8, 
                'GD': np.nan, 'pregnant': False, 'rig': 'omen-vr',},            
            {'date': '2026_06_16', 'scene': 'FiveTower_Switch_BlackoutDelay', 'session': 3, 'scan': np.nan, 'exp_day': 9, 
                'GD': np.nan, 'pregnant': False, 'rig': 'omen-vr',},
            {'date': '2026_06_17', 'scene': 'FiveTower_Stay_BlackoutDelay', 'session': 2, 'scan': np.nan, 'exp_day': 10, 
                'GD': np.nan, 'pregnant': False, 'rig': 'omen-vr',}, 
            {'date': '2026_06_18', 'scene': 'FiveTower_Switch_BlackoutDelay', 'session': 1, 'scan': np.nan, 'exp_day': 11, 
                'GD': np.nan, 'pregnant': False, 'rig': 'omen-vr',},
            {'date': '2026_06_19', 'scene': 'FiveTower_Stay_BlackoutDelay', 'session': 1, 'scan': np.nan, 'exp_day': 12, 
                'GD': np.nan, 'pregnant': False, 'rig': 'omen-vr',}, 
            {'date': '2026_06_20', 'scene': 'FiveTower_Switch_BlackoutDelay', 'session': 2, 'scan': np.nan, 'exp_day': 13, 
                'GD': np.nan, 'pregnant': False, 'rig': 'omen-vr',},
            {'date': '2026_06_21', 'scene': 'FiveTower_Stay_BlackoutDelay', 'session': 1, 'scan': np.nan, 'exp_day': 14, 
                'GD': np.nan, 'pregnant': False, 'rig': 'omen-vr',},
            {'date': '2026_06_22', 'scene': 'FiveTower_Switch_BlackoutDelay', 'session': 1, 'scan': np.nan, 'exp_day': 15, 
                'GD': np.nan, 'pregnant': False, 'rig': 'omen-vr',},
            {'date': '2026_06_23', 'scene': 'FiveTower_Stay_BlackoutDelay', 'session': 1, 'scan': np.nan, 'exp_day': 16, 
                'GD': np.nan, 'pregnant': False, 'rig': 'omen-vr',},
                ## Add remaining days below here!
    ),

    ## Add metadata for pp03 and ps04 using the same format as above
    'pp03': ({'date': '2026_06_05', 'scene': 'FiveTower_Stay', 'session': 1, 'scan': np.nan, 'exp_day': 1,
                'GD': np.nan, 'pregnant': False, 'rig': 'omen-vr',},
            {'date': '2026_06_06', 'scene': 'FiveTower_Stay', 'session': 1, 'scan': np.nan, 'exp_day': 2,
                'GD': np.nan, 'pregnant': False, 'rig': 'omen-vr',},
            {'date': '2026_06_07', 'scene': 'FiveTower_Switch_BlackoutDelay', 'session': 1, 'scan': np.nan, 'exp_day': 3,
                'GD': np.nan, 'pregnant': False, 'rig': 'omen-vr',},
            {'date': '2026_06_08', 'scene': 'FiveTower_Stay_BlackoutDelay', 'session': 1, 'scan': np.nan, 'exp_day': 4,
                'GD': np.nan, 'pregnant': False, 'rig': 'omen-vr',},
            {'date': '2026_06_14', 'scene': 'FiveTower_Switch_BlackoutDelay', 'session': 1, 'scan': np.nan, 'exp_day': 5,
                'GD': 5, 'pregnant': True, 'rig': 'omen-vr',},  
            {'date': '2026_06_15', 'scene': 'FiveTower_Stay_BlackoutDelay', 'session': 1, 'scan': np.nan, 'exp_day': 6,
                'GD': 6, 'pregnant': True, 'rig': 'omen-vr',},
            {'date': '2026_06_16', 'scene': 'FiveTower_Switch_BlackoutDelay', 'session': 1, 'scan': np.nan, 'exp_day': 7,
                'GD': 7, 'pregnant': True, 'rig': 'omen-vr',},  
            {'date': '2026_06_17', 'scene': 'FiveTower_Stay_BlackoutDelay', 'session': 2, 'scan': np.nan, 'exp_day': 8,
                'GD': 8, 'pregnant': True, 'rig': 'omen-vr',}, 
            {'date': '2026_06_18', 'scene': 'FiveTower_Switch_BlackoutDelay', 'session': 3, 'scan': np.nan, 'exp_day': 9,
                'GD': 9, 'pregnant': True, 'rig': 'omen-vr',},
            {'date': '2026_06_19', 'scene': 'FiveTower_Stay_BlackoutDelay', 'session': 3, 'scan': np.nan, 'exp_day': 10,
                'GD': 10, 'pregnant': True, 'rig': 'omen-vr',}, 
            {'date': '2026_06_20', 'scene': 'FiveTower_Switch_BlackoutDelay', 'session': 1, 'scan': np.nan, 'exp_day': 11,
                'GD': 11, 'pregnant': True, 'rig': 'omen-vr',},
            {'date': '2026_06_21', 'scene': 'FiveTower_Switch_BlackoutDelay', 'session': 1, 'scan': np.nan, 'exp_day': 12,
                'GD': 12, 'pregnant': True, 'rig': 'omen-vr',},
            {'date': '2026_06_22', 'scene': 'FiveTower_Stay_BlackoutDelay', 'session': 1, 'scan': np.nan, 'exp_day': 13,
                'GD': 13, 'pregnant': True, 'rig': 'omen-vr',},
            {'date': '2026_06_23', 'scene': 'FiveTower_Switch_BlackoutDelay', 'session': 1, 'scan': np.nan, 'exp_day': 14,
                'GD': 14, 'pregnant': True, 'rig': 'omen-vr',},
            {'date': '2026_06_24', 'scene': 'FiveTower_Stay_BlackoutDelay', 'session': 1, 'scan': np.nan, 'exp_day': 15,
                'GD': 15, 'pregnant': True, 'rig': 'omen-vr',},
            {'date': '2026_06_25', 'scene': 'FiveTower_Switch_BlackoutDelay', 'session': 1, 'scan': np.nan, 'exp_day': 16,
                'GD': 16, 'pregnant': True, 'rig': 'omen-vr',},
            
    ),

    'ps04': ({'date': '2026_07_06', 'scene': 'FiveTower_Stay', 'session': 2, 'scan': np.nan, 'exp_day': 1,
                'GD': np.nan, 'pregnant': False, 'rig': 'omen-vr',},
            {'date': '2026_07_07', 'scene': 'FiveTower_Stay', 'session': 2, 'scan': np.nan, 'exp_day': 2,
                'GD': np.nan, 'pregnant': False, 'rig': 'omen-vr',},
            {'date': '2026_07_08', 'scene': 'FiveTower_Switch_BlackoutDelay', 'session': 1, 'scan': np.nan, 'exp_day': 3,
                'GD': np.nan, 'pregnant': False, 'rig': 'omen-vr',},
            {'date': '2026_07_09', 'scene': 'FiveTower_Stay_BlackoutDelay', 'session': 1, 'scan': np.nan, 'exp_day': 4,
                'GD': np.nan, 'pregnant': False, 'rig': 'omen-vr',},
            {'date': '2026_07_17', 'scene': 'FiveTower_Switch_BlackoutDelay', 'session': 1, 'scan': np.nan, 'exp_day': 5,
                'GD': 6, 'pregnant': True, 'rig': 'omen-vr',},  
            {'date': '2026_07_18', 'scene': 'FiveTower_Stay_BlackoutDelay', 'session': 3, 'scan': np.nan, 'exp_day': 6,
                'GD': 7, 'pregnant': True, 'rig': 'omen-vr',},
            {'date': '2026_07_18', 'scene': 'FiveTower_Stay_BlackoutDelay', 'session': 4, 'scan': np.nan, 'exp_day': 6,
                'GD': 7, 'pregnant': True, 'rig': 'omen-vr',},
            {'date': '2026_07_19', 'scene': 'FiveTower_Switch_BlackoutDelay', 'session': 1, 'scan': np.nan, 'exp_day': 7,
                'GD': 8, 'pregnant': True, 'rig': 'omen-vr',},  
            {'date': '2026_07_20', 'scene': 'FiveTower_Stay_BlackoutDelay', 'session': 1, 'scan': np.nan, 'exp_day': 8,
                'GD': 9, 'pregnant': True, 'rig': 'omen-vr',}, 
            {'date': '2026_07_21', 'scene': 'FiveTower_Switch_BlackoutDelay', 'session': 4, 'scan': np.nan, 'exp_day': 9,
                'GD': 10, 'pregnant': True, 'rig': 'omen-vr',},
            {'date': '2026_07_22', 'scene': 'FiveTower_Stay_BlackoutDelay', 'session': 1, 'scan': np.nan, 'exp_day': 10,
                'GD': 11, 'pregnant': True, 'rig': 'omen-vr',}, 
            {'date': '2026_07_23', 'scene': 'FiveTower_Switch_BlackoutDelay', 'session': 1, 'scan': np.nan, 'exp_day': 11,
                'GD': 12, 'pregnant': True, 'rig': 'omen-vr',},
            

    )

}

## No need to edit below here

stanford = {
    # Behavior only animals for pregnancy pilot with RunningTraining -- here exp_day corresponds to GD

    '1780_02': ({'date': '25_05_2025', 'scene': 'RunningTraining_scan', 'session': 1, 'scan': np.nan, 'exp_day': 3, 'pregnant': True},
                {'date': '27_05_2025', 'scene': 'RunningTraining_scan',
                 'session': 1, 'scan': np.nan, 'exp_day': 5, 'pregnant': True},
                {'date': '29_05_2025', 'scene': 'RunningTraining_scan',
                 'session': 1, 'scan': np.nan, 'exp_day': 7, 'pregnant': True},
                {'date': '31_05_2025', 'scene': 'RunningTraining_scan',
                 'session': 1, 'scan': np.nan, 'exp_day': 9, 'pregnant': True},
                {'date': '02_06_2025', 'scene': 'RunningTraining_scan',
                 'session': 2, 'scan': np.nan, 'exp_day': 11, 'pregnant': True},
                {'date': '04_06_2025', 'scene': 'RunningTraining_scan',
                 'session': 1, 'scan': np.nan, 'exp_day': 13, 'pregnant': True},
                {'date': '06_06_2025', 'scene': 'RunningTraining_scan',
                    'session': 1, 'scan': np.nan, 'exp_day': 15, 'pregnant': True},
                ),

    '4855_04': ({'date': '31_05_2025', 'scene': 'RunningTraining_scan', 'session': 1, 'scan': np.nan, 'exp_day': 3, 'pregnant': False},
                {'date': '02_06_2025', 'scene': 'RunningTraining_scan',
                 'session': 1, 'scan': np.nan, 'exp_day': 5, 'pregnant': False},
                {'date': '04_06_2025', 'scene': 'RunningTraining_scan',
                 'session': 1, 'scan': np.nan, 'exp_day': 7, 'pregnant': False},
                {'date': '06_06_2025', 'scene': 'RunningTraining_scan',
                 'session': 1, 'scan': np.nan, 'exp_day': 9, 'pregnant': False},
                {'date': '08_06_2025', 'scene': 'RunningTraining_scan',
                 'session': 1, 'scan': np.nan, 'exp_day': 11, 'pregnant': False},
                {'date': '10_06_2025', 'scene': 'RunningTraining_scan',
                 'session': 1, 'scan': np.nan, 'exp_day': 13, 'pregnant': False},
                {'date': '12_06_2025', 'scene': 'RunningTraining_scan',
                 'session': 1, 'scan': np.nan, 'exp_day': 15, 'pregnant': False},
                ),

    '1781_06': ({'date': '31_05_2025', 'scene': 'RunningTraining_scan', 'session': 1, 'scan': np.nan, 'exp_day': 3, 'pregnant': False},
                {'date': '02_06_2025', 'scene': 'RunningTraining_scan',
                 'session': 1, 'scan': np.nan, 'exp_day': 5, 'pregnant': False},
                {'date': '04_06_2025', 'scene': 'RunningTraining_scan',
                 'session': 1, 'scan': np.nan, 'exp_day': 7, 'pregnant': False},
                {'date': '06_06_2025', 'scene': 'RunningTraining_scan',
                 'session': 1, 'scan': np.nan, 'exp_day': 9, 'pregnant': False},
                {'date': '08_06_2025', 'scene': 'RunningTraining_scan',
                 'session': 1, 'scan': np.nan, 'exp_day': 11, 'pregnant': False},
                {'date': '10_06_2025', 'scene': 'RunningTraining_scan',
                 'session': 1, 'scan': np.nan, 'exp_day': 13, 'pregnant': False},
                {'date': '12_06_2025', 'scene': 'RunningTraining_scan',
                 'session': 1, 'scan': np.nan, 'exp_day': 15, 'pregnant': False},
                ),

    '1781_07': ({'date': '29_05_2025', 'scene': 'RunningTraining_scan', 'session': 1, 'scan': np.nan, 'exp_day': 3, 'pregnant': True},
                {'date': '31_05_2025', 'scene': 'RunningTraining_scan',
                 'session': 1, 'scan': np.nan, 'exp_day': 5, 'pregnant': True},
                {'date': '02_06_2025', 'scene': 'RunningTraining_scan',
                 'session': 1, 'scan': np.nan, 'exp_day': 7, 'pregnant': True},
                {'date': '04_06_2025', 'scene': 'RunningTraining_scan',
                 'session': 1, 'scan': np.nan, 'exp_day': 9, 'pregnant': True},
                {'date': '06_06_2025', 'scene': 'RunningTraining_scan',
                'session': 1, 'scan': np.nan, 'exp_day': 11, 'pregnant': True},
                {'date': '08_06_2025', 'scene': 'RunningTraining_scan',
                'session': 1, 'scan': np.nan, 'exp_day': 13, 'pregnant': True},
                {'date': '10_06_2025', 'scene': 'RunningTraining_scan',
                 'session': 1, 'scan': np.nan, 'exp_day': 15, 'pregnant': True},
                ),
}
